<?php
// $id$

/**
 * @file
 * A module exemplifying Drupal coding practices and API's
 * 
 * This module provides a block that lists all of the
 * installed modules.
 *
 */
 
/**
 * Implements hook_help().
 */
function first_help($path, $arg) {
	if ($path == 'admin/help#first') {
		return t('A demonstration module.');
	}
}

/**
 * Implements hook_block_info().
 */
function first_block_info() {
	$blocks = array();
	
	$blocks['list_modules'] = array(
		'info' => t('A listing of all of the enabled modules.'),
		'cache' => DRUPAL_NO_CACHE,
	);
	
	return $blocks;
}

/**
 * Implements hook_block_view()
 *
 * returns 2 items: 1) subject; block name, 2) content formatted as html
 */
function first_block_view() {
	if ($block_name == 'list_modules') {
		$list = module_list(); // Drupal function which returns an associative array of module names
		
		$theme_args = array('items' => $list, 'type' => 'ol');
		$content = theme('item_list', $theme_args); // theme args= 1) the name of the theme operation, 2) an ass. array of vars to pass
		
		$block = array(
			'subject' => t('Enabled Modules'),
			'content' => $content, // comma required
		);
		return $block;
	}
}